[window]

startup_mode = "maximized"

opacity = 0.9

padding.x = 0
padding.y = 2

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"


[font]

normal.family = "ShureTechMono Nerd Font"
bold.family = "ShureTechMono Nerd Font"
italic.family = "ShureTechMono Nerd Font"
bold_italic.family = "ShureTechMono Nerd Font"

size = 13.0


